"""
generate_charts.py
Executes all 8 charts from Section 3 of Day_11/README.md and saves them as images in Day_11/images/
"""

from pathlib import Path
import matplotlib
matplotlib.use("Agg")  # Non-interactive backend for headless image generation
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Setup paths
base_dir = Path(__file__).resolve().parent.parent
img_dir = base_dir / "images"
img_dir.mkdir(parents=True, exist_ok=True)
csv_file = base_dir / "Sales.csv"

print(f"Loading data from: {csv_file}")
df = pd.read_csv(csv_file)

# Basic cleaning
for col in ["Price Per Toy", "Total Line Revenue", "Total COGS"]:
    df[col] = df[col].astype(str).str.replace("$", "", regex=False).str.strip().astype(float)
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y")
df["Line_Profit"] = df["Total Line Revenue"] - df["Total COGS"]
df["YearMonth"] = df["Date"].dt.to_period("M")

# ----------------- CHART 1: Horizontal Bar Chart -----------------
toy_sales = df.groupby("Toy Name")["Total Line Revenue"].sum().sort_values(ascending=True)
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.barh(toy_sales.index, toy_sales.values, color="#1f77b4", edgecolor="black", height=0.65)
ax.set_title("Total Revenue Generated by Toy Name (2010 - 2012)", fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Total Revenue (USD $)", fontsize=12)
ax.set_ylabel("Toy Name", fontsize=12)
ax.grid(axis="x", linestyle="--", alpha=0.7)
for bar in bars:
    w = bar.get_width()
    ax.text(w + 80, bar.get_y() + bar.get_height() / 2, f"${w:,.2f}", va="center", ha="left", fontsize=9, fontweight="medium")
ax.set_xlim(0, max(toy_sales.values) * 1.15)
plt.tight_layout()
chart1_path = img_dir / "chart1_revenue_by_toy.png"
plt.savefig(chart1_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart1_path.name}")

# ----------------- CHART 2: Histogram & Mean/Median -----------------
fig, ax = plt.subplots(figsize=(9, 5))
counts, bins, patches = ax.hist(df["Purchaser Age"], bins=20, color="#2ca02c", edgecolor="white", alpha=0.85)
mean_age = df["Purchaser Age"].mean()
median_age = df["Purchaser Age"].median()
ax.axvline(mean_age, color="red", linestyle="--", linewidth=2, label=f"Mean: {mean_age:.1f} yrs")
ax.axvline(median_age, color="blue", linestyle=":", linewidth=2, label=f"Median: {median_age:.0f} yrs")
ax.set_title("Customer Age Distribution at Checkout", fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Purchaser Age (Years)", fontsize=12)
ax.set_ylabel("Number of Transactions", fontsize=12)
ax.legend(loc="upper right", frameon=True)
ax.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
chart2_path = img_dir / "chart2_age_distribution.png"
plt.savefig(chart2_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart2_path.name}")

# ----------------- CHART 3: Line Chart (Seasonality) -----------------
monthly_trend = df.groupby("YearMonth")["Total Line Revenue"].sum()
x_labels = [str(p) for p in monthly_trend.index]
y_values = monthly_trend.values
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(x_labels, y_values, marker="o", color="#d62728", linewidth=2.5, markersize=6, label="Monthly Revenue")
ax.set_title("Monthly Toy Store Sales Revenue (2010 - 2012)", fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Year-Month", fontsize=12)
ax.set_ylabel("Total Revenue ($)", fontsize=12)
ax.set_xticks(range(0, len(x_labels), 2))
ax.set_xticklabels([x_labels[i] for i in range(0, len(x_labels), 2)], rotation=45, ha="right")
ax.grid(True, linestyle="--", alpha=0.6)
ax.legend(loc="upper left")
max_rev = max(y_values)
max_idx = list(y_values).index(max_rev)
ax.annotate(
    "Holiday Season Surge!",
    xy=(max_idx, max_rev),
    xytext=(max_idx - 4, max_rev + 400),
    arrowprops=dict(facecolor="black", shrink=0.08, width=1.5, headwidth=8),
    fontsize=10,
    fontweight="bold"
)
plt.tight_layout()
chart3_path = img_dir / "chart3_monthly_sales_trend.png"
plt.savefig(chart3_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart3_path.name}")

# ----------------- CHART 4: Scatter Plot (Revenue vs COGS) -----------------
fig, ax = plt.subplots(figsize=(8, 6))
for company, color in [("Duplo", "#1f77b4"), ("Lego", "#ff7f0e")]:
    mask = df["Toy Company"] == company
    ax.scatter(df.loc[mask, "Total COGS"], df.loc[mask, "Total Line Revenue"], c=color, label=company, alpha=0.65, edgecolors="none", s=50)
ax.set_title("Total Line Revenue vs. Wholesale Cost (COGS)", fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Total COGS (Wholesale Cost in $)", fontsize=12)
ax.set_ylabel("Total Line Revenue (Retail Price in $)", fontsize=12)
ax.legend(title="Toy Brand", loc="upper left")
ax.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
chart4_path = img_dir / "chart4_revenue_vs_cogs.png"
plt.savefig(chart4_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart4_path.name}")

# ----------------- CHART 5: Seaborn Countplot -----------------
sns.set_theme(style="whitegrid", palette="deep")
fig, ax = plt.subplots(figsize=(10, 5))
sns.countplot(data=df, x="Payment", hue="Member?", order=df["Payment"].value_counts().index, ax=ax)
ax.set_title("Payment Methods Segmented by Customer Loyalty Membership", fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Payment Tender Method", fontsize=12)
ax.set_ylabel("Transaction Count", fontsize=12)
ax.legend(title="Loyalty Member?", loc="upper right")
plt.tight_layout()
chart5_path = img_dir / "chart5_payment_by_membership.png"
plt.savefig(chart5_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart5_path.name}")

# ----------------- CHART 6: Boxplot & Violin Plot -----------------
sns.set_theme(style="whitegrid")
fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(14, 5))
sns.boxplot(data=df, x="Toy Company", y="Purchaser Age", palette=["#4c72b0", "#dd8452"], ax=ax1, width=0.4)
ax1.set_title("Boxplot: Age Spread & Quartiles", fontsize=12, fontweight="bold")
ax1.set_xlabel("Toy Brand", fontsize=11)
ax1.set_ylabel("Purchaser Age", fontsize=11)

sns.violinplot(data=df, x="Toy Company", y="Purchaser Age", palette=["#4c72b0", "#dd8452"], inner="quartile", ax=ax2)
ax2.set_title("Violin Plot: Age Probability Density", fontsize=12, fontweight="bold")
ax2.set_xlabel("Toy Brand", fontsize=11)
ax2.set_ylabel("Purchaser Age", fontsize=11)

fig.suptitle("Purchaser Age Comparison: Duplo vs. Lego Buyers", fontsize=15, fontweight="bold", y=1.02)
plt.tight_layout()
chart6_path = img_dir / "chart6_age_comparison_box_violin.png"
plt.savefig(chart6_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart6_path.name}")

# ----------------- CHART 7: Correlation Heatmap -----------------
numeric_cols = ["Price Per Toy", "Units Sold", "Total Line Revenue", "Total COGS", "Line_Profit", "Purchaser Age"]
corr_matrix = df[numeric_cols].corr()
fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="vlag", vmin=-1, vmax=1, linewidths=0.5, cbar_kws={"label": "Pearson Correlation Coefficient (r)"}, ax=ax)
ax.set_title("Pairwise Correlation Matrix of Financial Metrics", fontsize=14, fontweight="bold", pad=15)
plt.tight_layout()
chart7_path = img_dir / "chart7_correlation_heatmap.png"
plt.savefig(chart7_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart7_path.name}")

# ----------------- CHART 8: Pivot Heatmap -----------------
pivot_avg = pd.pivot_table(data=df, values="Total Line Revenue", index="Toy Company", columns="Payment", aggfunc="mean")
fig, ax = plt.subplots(figsize=(10, 4))
sns.heatmap(pivot_avg, annot=True, fmt=".2f", cmap="YlGnBu", linewidths=1, cbar_kws={"label": "Average Line Revenue ($)"}, ax=ax)
ax.set_title("Average Ticket Size ($) by Brand & Payment Method", fontsize=14, fontweight="bold", pad=15)
ax.set_xlabel("Payment Method", fontsize=11)
ax.set_ylabel("Toy Brand", fontsize=11)
plt.tight_layout()
chart8_path = img_dir / "chart8_pivot_ticket_size_heatmap.png"
plt.savefig(chart8_path, dpi=200)
plt.close(fig)
print(f"Saved: {chart8_path.name}")

# ----------------- DASHBOARD -----------------
from sales_analytics_pipeline import load_and_clean_data, generate_visual_dashboard
pipeline_df = load_and_clean_data(csv_file)
dash_path = img_dir / "sales_analytics_dashboard.png"
generate_visual_dashboard(pipeline_df, output_path=str(dash_path))
print(f"Saved: {dash_path.name}")
print("All charts successfully generated!")
